"use strict";
exports.__esModule = true;
var Employee_1 = require("./Classes/Employee");
var EmployeeRegister_1 = require("./Classes/EmployeeRegister");
var employee = new Employee_1.Employee(450, "tester yamamura", 23);
var secondEmployer = new Employee_1.Employee(3434, "reasd asdas", 331);
console.log(employee.getSalary());
employee.setSalary(50000);
console.log(employee.getSalary());
var er = new EmployeeRegister_1.EmployeeRegister([employee]);
er.addEmployee(secondEmployer);
console.log(er.getAllEmployees());
er.deleteEmployee(employee.employeeId);
console.log(er.getAllEmployees());
er.updateById(secondEmployer.employeeId, new Employee_1.Employee(233333333, "test update", 34));
console.log(er.getAllEmployees());
er.addEmployee(new Employee_1.Employee(3333333, "1. dsfs", 3222));
er.addEmployee(new Employee_1.Employee(22222, "2. dsfs", 2));
er.addEmployee(new Employee_1.Employee(313, "3. dsfs", 32));
er.sortBySalary(false);
console.log(er.getAllEmployees());
